### ISSUE TITLE
本地数据存储选型

### ISSUE THREAD

**Issue by TooBug** [TooNote/TooNote#44]
- localStorage
- indexedDB
- sqlLite
- PouchDB
- fs

**Comment by TooBug** [comment]
PouchDB基本出局，原因：

- 服务端不支持按用户鉴权，所以不能同构
- 以文档为单位，部分字段查询不支持
- 按条件查询比较麻烦

**Comment by xbotao** [comment]
提交这么多特性，都是要做的吗？ 作者是要开源，还是做收费的啊

**Comment by TooBug** [comment]
@xbotao 是的，都是要做的。客户端开源，服务端不开源。云服务不排除收费的可能性，但是一定会有免费服务，也可以选择不使用云服务。

**Comment by xbotao** [comment]
@TooBug 有没有可能开源服务端的一小部分，简单的备份同步功能，然后让用户在自己的私有服务器上搭建呢

**Comment by TooBug** [comment]
@xbotao 暂时没有精力，服务端的开源要考虑的因素比较多，以后再做打算了。可能也不排除有企业版+社区版的可能性，也有可能是开放协议，大家可以自己实现服务端。等客户端先稳定之后再说了。

**Comment by TooBug** [comment]
最终选定使用realm。
