### ISSUE TITLE
讨论：云端笔记加密

### ISSUE THREAD

**Issue by TooBug** [TooNote/TooNote#50]
目前云端笔记内容是没做加密的，理论上我可以在服务器上查看任何笔记内容。虽然从云内测开始至今，我只出于调试目的查看过我自己的笔记内容，但是如果我说我从来没有看过别人的笔记内容，估计会有人不信。

出于对云服务本能地不信任，考虑将云端笔记内容进行加密。

- 加密方式：暂定AES（crypto-js/aes，应该是AES256吧）
- 密钥保管：用户自行保密，云端不做存储
- 笔记内容：本地解密后明文，云端全部只存密文
- 其它后果：无法进行云端搜索，**密码忘记后笔记内容将永久丢失**

注：再强调一次，**密码忘记后笔记内容将永久丢失**，因为云端只存密文，而密钥由客户保管，全程只在客户端加密解密使用。

问：

1. 你是否信任这样的加密方式？
2. 如果不信任，要如何才能信任？
3. 密码忘记后笔记内容永久丢失的风险你愿意承担吗？还是情愿不加密，忘记密码后可以找回笔记内容？

或者：

你有更好的加密方式吗？

**Comment by dingXX** [comment]
对于连支付密码都能忘的人来说，最大的问题是不相信自己能记住这个密钥(输入法告诉我说叫yue，哈哈)啊！！能找回密钥吗？？？

**Comment by TooBug** [comment]
@dingXX 如果能找回密钥，就意味着云端存有密钥，也就意味着在云端可以随时不经用户授权解密查看笔记内容。

**Comment by myst729** [comment]
@TooBug 用不对称加密就不怕另一边随便看了

**Comment by TooBug** [comment]
@myst729 求具体一点？哪边存私钥哪边存公钥？加密和解密分别是在哪里进行？

**Comment by myst729** [comment]
仔细想了想好像不太对，通常的 RSA 加密做的事情跟你说的这个不是一回事。确实是密钥丢失就跪了 🤷‍♂️

**Comment by easthing** [comment]
数字钱包丢了密码也是无解，只能提示用户做好密码备份。

**Comment by LindaWhite** [comment]
如果密码忘记，找不回了么。。。

**Comment by Yi-love** [comment]
可以使用指纹识别吗？

**Comment by TooBug** [comment]
@LindaWhite 可以重置密码，但是用密码加密的文件就跪了。

**Comment by TooBug** [comment]
@Yi-love 小伙子，我喜欢你的思维。

**Comment by TooBug** [comment]
也许可以找一个秘密且不会遗忘的东西作为密钥，比如身份证号？
