### ISSUE TITLE
请求增加文章搜索关键字的功能

### ISSUE THREAD

**Issue by ellyliang** [TooNote/TooNote#55]
需求是这样的，由于我复制了一篇很长的文章，里边各种英文，符号，中文组成，然后我要找到一个关键字，然鹅我要一直拉上拉下，想说作者能否造福一下，增加一个搜索关键字的功能，灰常感谢作者

**Comment by TooBug** [comment]
https://github.com/TooNote/MdEditor/commit/c8079173af21015ca98c0f066378ce340590f628

**Comment by TooBug** [comment]
似乎在1.0中坏掉了
