### ISSUE TITLE
项目怎么跑不起来？！！！

### ISSUE THREAD

**Issue by iTwangcj** [TooNote/TooNote#57]
![image](https://user-images.githubusercontent.com/7961076/28244397-df8862e8-6a1c-11e7-9911-3c74b3b9f5df.png)

**Comment by TooBug** [comment]
麻烦提供一下electron的版本和webpack的版本。

**Comment by TooBug** [comment]
还有使用的是哪个分支的代码？

**Comment by iTwangcj** [comment]
您好，
      代码使用的就是master, 
      electron: v1.6.11
      webpack: 2.5.1

**Comment by TooBug** [comment]
你重新安装一下依赖试试。安装下来应该是webpack 3.3.0才对。

另外webpack 3.3.0的ModuleConcatenationPlugin好像有问题，可以将webpack.config.js第62行先屏蔽，然后再试一下，如果有问题请再反馈给我。

**Comment by iTwangcj** [comment]
可以了 thanks
