### ISSUE TITLE
微信小程序

### ISSUE THREAD

**Issue by huarxia** [TooNote/TooNote#59]
请问使用github登录后，有个微信绑定码，应该怎么绑定微信小程序？已经误点了创建账号，能够删除绑定微信小程序的账号么？我想将该账号绑定到我的工作微信上。谢谢

**Comment by TooBug** [comment]
微信小程序中搜索 TooNote ，进去后千万不要手快，注意看，点绑定已有账号，然后输入绑定码即可。

**Comment by TooBug** [comment]
不好意思，我看邮件的时候好像没有提到已经创建账号。麻烦提供一下你的github用户名，我帮你删掉微信的登录信息，然后你再试一次。

**Comment by huarxia** [comment]
github: huarxia  微信：liubiao0810  帮忙删掉下微信登录信息吧，我想重新绑定到github这个账号上

**Comment by TooBug** [comment]
不好意思，麻烦你再提供一下微信的昵称，如果可以的话，微信头像也发一个？

因为我这边只能拿到openId、昵称和头像，没有办法拿到微信号，所以不知道对应的是哪一个微信账号。

**Comment by huarxia** [comment]
昵称: 花夏  

![wechatimg6](https://user-images.githubusercontent.com/11221788/28355767-020269d6-6c98-11e7-8964-2d318b6fc949.jpeg)

**Comment by TooBug** [comment]
已经帮你合并了，试一下看对不对。

**Comment by huarxia** [comment]
还看不出来，请看60号问题
