### ISSUE TITLE
无法新建笔记

### ISSUE THREAD

**Issue by huarxia** [TooNote/TooNote#60]
百度网盘下载的最新mac版，无法新建笔记，也无法像  test \ 123 这样的文件夹归类存放

**Comment by TooBug** [comment]
更新一下新版试试，今天下午刚发布了0.3.1版。https://pan.baidu.com/s/1slrkdQH#list/path=%2Frelease%2FTooNote%2F0.3.1&parentPath=%2Frelease

**Comment by huarxia** [comment]
<img width="1198" alt="wx20170720-102546 2x" src="https://user-images.githubusercontent.com/11221788/28397704-dc9bdabc-6d35-11e7-9ce4-41a57fff6236.png">


一点反应没有

**Comment by TooBug** [comment]
是不是有旧版本数据缓存？方便的话右键点应用图标，点显示包内容，然后找到Resources/app/electron.js，把里面第28行，换成

```javascript
if(1){
```

然后重启，看看调试工具是否有报错。方便的话，可以把Application Tab下，localstorage的内容邮件一下给我？i#toobug.net

**Comment by huarxia** [comment]
hi，已经发给你了

**Comment by huarxia** [comment]
通过作者的修复，已经好使了，我测试下同步微信小程序哈~~
