### ISSUE TITLE
微信小程序与githu账号去除绑定未成功

### ISSUE THREAD

**Issue by huarxia** [TooNote/TooNote#61]
![wechatimg8](https://user-images.githubusercontent.com/11221788/28452475-7ad2775a-6e25-11e7-9888-6444de7b1b25.jpeg)

<img width="1152" alt="wx20170721-145925 2x" src="https://user-images.githubusercontent.com/11221788/28452476-7e84a4ea-6e25-11e7-91a6-e744f0f30276.png">

**Comment by TooBug** [comment]
再试一下？

**Comment by huarxia** [comment]
可以了，谢谢~~
