### ISSUE TITLE
笔记列表删空之后就无法再建新笔记

### ISSUE THREAD

**Issue by favers** [TooNote/TooNote#65]
![image](https://user-images.githubusercontent.com/19677784/28808785-613b62ae-76b1-11e7-85cf-61265460ca08.png)

**Comment by TooBug** [comment]
好的，尽快修复。:)

**Comment by TooBug** [comment]
@favers 你删除后有尝试新建笔记吗？还是只是在编辑器中输入文字而已？

删除后因为没有笔记，需要点击菜单，新建才会出现新的笔记的。

**Comment by favers** [comment]
@TooBug 就是从菜单进去点击新建也是没有反应。

**Comment by TooBug** [comment]
这样吧，你先右键点击app图标，显示包内容，然后找到`Contents/Resources/app/electron.js`，将第28行替换成

```
if(1){
```

然后打开应用，会看到调试工具，点`Application`面板，左侧`localstorage`，将里面的数据清除，然后重新启动试试是否可以恢复。

最近加了一些笔记全部清理掉之后的保护逻辑，还没发新版本。

**Comment by favers** [comment]
@TooBug 这样处理倒是可以恢复，这个笔记很好用，以后可否让这个笔记支持图床呢，感觉现在现在在这里面写完，要直接复制到其他地方相对于来说图片处理太麻烦，假如可以支持配置七牛图床，体验将会更好一些。

**Comment by TooBug** [comment]
@favers 图片的支持会很快有，支持将图片一并保存到云端。但是应该不会允许作为图床使用。你的使用场景是什么呢？

可以到 #24 说明一下，继续讨论。这个issue我先关掉了。
